version: '3.3'

networks:
  net-backend:
    driver: bridge

services:
  db:
    container_name: vivo-api-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=vivoapi
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=12345
      - TZ=America/Recife
    networks:
      - net-backend
    ports:
      - 3306:3306

  rabbitmq:
    container_name: vivo-api-rabbitmq
    image: rabbitmq:3.8.4-rc.3-management
    networks:
      - net-backend
    ports:
      - 15672:15672
      - 5672:5672

#  vivo-api:
#    container_name: vivo-api-server
#    build: .
#    depends_on:
#      - db
#    networks:
#      - net-backend
#    ports:
#      - 8080:8080